name: Purge jsDelivr Cache

on:
  push:
    paths:
      - 'games.json'   # 只有 games.json 文件变化时才触发
  workflow_dispatch:   # 允许手动触发

jobs:
  purge:
    runs-on: ubuntu-latest
    steps:
      - name: Purge jsDelivr cache
        run: |
          curl -X GET "https://purge.jsdelivr.net/gh/131474/CCLY@main/games.json"
